# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2509d95ba116a20c6c57c21cec297d45ce7969de0cc6fd325488e835f65ef54547364527379a6dc112094344b6343d1ba766c9952ed410e3082fa1b55b53c211

test:
  secret_key_base: 8d3af1c5a788313b1fd13bd6c38bbf155bbd1ad51ce0e5b7f2f98cfe391994597f1ab29b72a0d0d54cc49c8780b6ce9a8dd6f2fa04924755c04b7a2ec3d9be8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
